/**
 * Style Dictionary v4 config
 * Builds tokens/generated/variables.css — single file, three sections:
 *   1. :root { }                              — light (all tokens)
 *   2. [data-theme="dark"], .dark { }         — dark overrides
 *   3. @media prefers-color-scheme: dark { }  — OS-level dark fallback
 *
 * Source: tokens/base/*.json  (W3C DTCG format: $type, $value)
 * Output: tokens/generated/variables.css
 */

import StyleDictionary from 'style-dictionary'
import { promises as fs } from 'fs'

const GENERATED = 'tokens/generated'

// ── Custom format: variable declarations only (no selector wrapper) ──────────
StyleDictionary.registerFormat({
  name: 'css/vars',
  format: async ({ dictionary }) => {
    return dictionary.allTokens
      .map(token => `  --${token.name}: ${token.$value};`)
      .join('\n')
  },
})

// ── Light build — all tokens ─────────────────────────────────────────────────
const sdLight = new StyleDictionary({
  source: [
    'tokens/base/color.json',
    'tokens/base/color-system.json',
    'tokens/base/spacing.json',
    'tokens/base/typography.json',
    'tokens/base/radii.json',
    'tokens/base/shadow.json',
    'tokens/base/motion.json',
    'tokens/base/z-index.json',
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: `${GENERATED}/`,
      files: [{ destination: '_light.css', format: 'css/vars' }],
    },
  },
})

// ── Dark build — color + shadow overrides only ───────────────────────────────
const sdDark = new StyleDictionary({
  source: ['tokens/base/color-dark.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: `${GENERATED}/`,
      files: [{ destination: '_dark.css', format: 'css/vars' }],
    },
  },
})

// ── Build ────────────────────────────────────────────────────────────────────
await fs.mkdir(GENERATED, { recursive: true })
await sdLight.buildAllPlatforms()
await sdDark.buildAllPlatforms()

// ── Combine into single variables.css ────────────────────────────────────────
const light = (await fs.readFile(`${GENERATED}/_light.css`, 'utf-8')).trimEnd()
const dark  = (await fs.readFile(`${GENERATED}/_dark.css`,  'utf-8')).trimEnd()

const darkIndented = dark.split('\n').map(l => '  ' + l).join('\n')

const output = `/**
 * Design Token CSS Variables — generated by Style Dictionary
 * Do not edit directly. Source: tokens/base/*.json
 * Regenerate: npm run tokens
 */

:root {
${light}
}

[data-theme="dark"],
.dark {
${dark}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${darkIndented}
  }
}
`

await fs.writeFile(`${GENERATED}/variables.css`, output)
await fs.unlink(`${GENERATED}/_light.css`)
await fs.unlink(`${GENERATED}/_dark.css`)

console.log('✅ tokens/generated/variables.css')
