import StyleDictionary from 'style-dictionary'

/**
 * Custom transformer: converts W3C DTCG cubicBezier arrays/strings to CSS cubic-bezier()
 */
StyleDictionary.registerTransform({
  name: 'cubicBezier/css',
  type: 'value',
  filter: (token) => token.$type === 'cubicBezier' || token.type === 'cubicBezier',
  transform: (token) => {
    const v = token.$value ?? token.value
    if (Array.isArray(v)) {
      return `cubic-bezier(${v.join(', ')})`
    }
    return v
  },
})

/**
 * Custom transformer: fontFamily array → CSS font-family string
 */
StyleDictionary.registerTransform({
  name: 'fontFamily/css',
  type: 'value',
  filter: (token) => token.$type === 'fontFamily' || token.type === 'fontFamily',
  transform: (token) => {
    const v = token.$value ?? token.value
    if (Array.isArray(v)) return v.join(', ')
    return v
  },
})

/**
 * Custom transform group: extends css with our custom transforms
 */
StyleDictionary.registerTransformGroup({
  name: 'css/custom',
  transforms: [
    'attribute/cti',
    'name/kebab',
    'time/seconds',
    'html/icon',
    'size/rem',
    'color/css',
    'asset/url',
    'fontFamily/css',
    'cubicBezier/css',
    'content/quote',
  ],
})

/**
 * Custom format: outputs semantic light/dark tokens as CSS custom properties
 * with [data-theme="light"] and [data-theme="dark"] selectors.
 */
StyleDictionary.registerFormat({
  name: 'css/semantic-themes',
  format: ({ dictionary }) => {
    const allTokens = dictionary.allTokens

    const primitiveTokens = allTokens.filter(
      (t) => t.path[0] === 'color' && t.path[1] === 'primitive'
    )
    const lightTokens = allTokens.filter(
      (t) => t.path[0] === 'color' && t.path[1] === 'semantic' && t.path[2] === 'light'
    )
    const darkTokens = allTokens.filter(
      (t) => t.path[0] === 'color' && t.path[1] === 'semantic' && t.path[2] === 'dark'
    )
    const otherTokens = allTokens.filter(
      (t) => t.path[0] !== 'color' || (t.path[1] !== 'primitive' && t.path[1] !== 'semantic')
    )

    const toVar = (token) => `  --${token.name}: ${token.$value ?? token.value};`

    const lightVarName = (token) => {
      // strip "semantic-light-" prefix → "color-semantic-light-bg-base" → "color-bg-base"
      const name = token.name
        .replace(/^color-semantic-light-/, 'color-')
      return name
    }
    const darkVarName = (token) => {
      const name = token.name
        .replace(/^color-semantic-dark-/, 'color-')
      return name
    }

    const lines = []
    lines.push('/* ============================================')
    lines.push('   Design System — Generated CSS Custom Properties')
    lines.push('   DO NOT EDIT — generated by Style Dictionary')
    lines.push('   ============================================ */')
    lines.push('')

    // Root: primitive colors + non-color tokens
    lines.push(':root {')
    primitiveTokens.forEach((t) => lines.push(toVar(t)))
    lines.push('')
    otherTokens.forEach((t) => lines.push(toVar(t)))
    lines.push('}')
    lines.push('')

    // Light theme (default)
    lines.push('[data-theme="light"], :root:not([data-theme="dark"]) {')
    lightTokens.forEach((t) => {
      const name = lightVarName(t)
      lines.push(`  --${name}: ${t.$value ?? t.value};`)
    })
    lines.push('}')
    lines.push('')

    // Dark theme
    lines.push('[data-theme="dark"] {')
    darkTokens.forEach((t) => {
      const name = darkVarName(t)
      lines.push(`  --${name}: ${t.$value ?? t.value};`)
    })
    lines.push('}')
    lines.push('')

    return lines.join('\n')
  },
})

const sd = new StyleDictionary({
  source: ['tokens/base/*.json'],
  platforms: {
    css: {
      transformGroup: 'css/custom',
      prefix: '',
      buildPath: 'src/tokens/generated/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/semantic-themes',
        },
      ],
    },
  },
})

await sd.buildAllPlatforms()
