import type { Meta, StoryObj } from '@storybook/react'
import { Textarea } from './index'

const meta: Meta<typeof Textarea> = {
  title: 'Forms/Textarea',
  component: Textarea,
  tags: ['autodocs'],
  argTypes: {
    resize: { control: 'select', options: ['none', 'vertical', 'horizontal', 'both'] },
    disabled: { control: 'boolean' },
    showCount: { control: 'boolean' },
    rows: { control: 'number' },
    label: { control: 'text' },
    helperText: { control: 'text' },
    error: { control: 'text' },
    placeholder: { control: 'text' },
  },
}

export default meta
type Story = StoryObj<typeof Textarea>

export const Default: Story = {
  args: {
    label: 'Project description',
    placeholder: 'Describe your project…',
    helperText: 'A brief overview for collaborators.',
  },
}

export const WithError: Story = {
  args: {
    label: 'Bio',
    defaultValue: 'x',
    error: 'Bio must be at least 20 characters.',
  },
}

export const WithCounter: Story = {
  args: {
    label: 'Post content',
    placeholder: 'What\'s on your mind?',
    showCount: true,
    maxLength: 280,
    helperText: 'Supports basic markdown.',
  },
}

export const CounterOverLimit: Story = {
  args: {
    label: 'Tweet',
    defaultValue: 'This is a very long piece of text that intentionally exceeds the character limit to demonstrate the over-limit counter state in red.',
    showCount: true,
    maxLength: 100,
  },
}

export const Disabled: Story = {
  args: {
    label: 'System notes',
    defaultValue: 'Auto-generated by the deployment pipeline. Read only.',
    helperText: 'This field is managed automatically.',
    disabled: true,
  },
}

export const ResizeVariants: Story = {
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', width: '400px' }}>
      <Textarea label="No resize" placeholder="Cannot be resized." resize="none" rows={3} />
      <Textarea label="Vertical (default)" placeholder="Resize vertically only." resize="vertical" rows={3} />
      <Textarea label="Horizontal" placeholder="Resize horizontally only." resize="horizontal" rows={3} />
      <Textarea label="Both" placeholder="Resize in any direction." resize="both" rows={3} />
    </div>
  ),
}

export const AllStates: Story = {
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', width: '400px' }}>
      <Textarea label="Default" placeholder="Placeholder text" />
      <Textarea label="With value" defaultValue="Some content here." />
      <Textarea label="With helper" placeholder="Write something…" helperText="Markdown is supported." />
      <Textarea label="Error state" defaultValue="bad" error="Content is too short." />
      <Textarea label="With counter" placeholder="Write up to 160 characters…" showCount maxLength={160} />
      <Textarea label="Disabled" defaultValue="Read-only content." disabled />
    </div>
  ),
}

export const TallRows: Story = {
  args: {
    label: 'Cover letter',
    placeholder: 'Write your cover letter…',
    rows: 8,
    showCount: true,
    maxLength: 1000,
    helperText: 'Keep it concise and compelling.',
  },
}
